In [1]:
first_num=int(input("Enter first Number: "))
sec_number= int(input("Enter Second Number: "))
third_number= int(input("Enter third Number: "))
fourth_number=int(input("Enter fourth Number: "))


file = open("numbers.txt","w")
file.write(f"{first_num} {sec_number} {third_number} {fourth_number}") #write the inputted numbers to the file
file.close()

In [10]:
#Write a program to ask a student for their percentage mark and convert this to a grade 

percentage=float(input("Enter marks obtained: "))

def mark_grade():
    if percentage > 90:
        print("Passed with A grade")
    elif percentage >= 70 and percentage < 90:
        print("Passed with B grade")
    elif percentage >= 60 and percentage < 70:
        print("Passed with C grade")
    elif percentage >= 50 and percentage < 60:
        print("passed with D Grade")
    else:
        print("You failed")


mark_grade()

Passed with A grade


In [17]:
# 1.Create a 1D array of numbers from 0 to 9
import numpy as np
x = np.arange(10)
print("This is a array from 0 to 10:")
print(" ")
print(x)

This is a array from 0 to 10:
 
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 2.Create a 3×3 NumPy array of all Boolean value Trues


In [18]:
# 3.Extract all odd numbers from array of 1-10
array = np.arange(1, 10) 
print(array[array%2==1])

[1 3 5 7 9]


In [19]:
# 4.Replace all odd numbers in an array of 1-10 with the value -1
task4_array= np.arange(1, 10)  

task4_array[task4_array%2==1] = -1  

[-1  2 -1  4 -1  6 -1  8 -1]


In [27]:
# 5. Convert a 1D array to a 2D array with 2 rows
#import numpy as np
array = np.array([1, 2, 3, 4, 5,6])
newArray = array.reshape(3, 2) 
print(newArray)


[[1 2]
 [3 4]
 [5 6]]


In [35]:
# 6. Create two arrays a and b, stack these two arrays vertically use the np.dot and np.sum to calculate totals
a = np.arange (1,10).reshape (3,3) 
b = np.arange (1,10).reshape (3,3)
dot= np.dot(a, b)
print(dot)
# sum=np.sum(a,b)
# print(sum)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [34]:

a = np.arange (1,10).reshape (3,3) 
b = np.arange (1,10).reshape (3,3) 
c = np.dot(a, b)
sum = np.sum(c) 
print(sum)

729
